default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000


development:
  <<: *default
  database: devans-app_development


test: &test
  <<: *default
  database: devans-app_test


production:
  <<: *default
  database: devans-app_production

cucumber:
  <<: *test
